version: '3'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test

  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - "3000:3000"
    working_dir: /usr/www
    volumes:
      - ./app:/usr/www

#docker-compose exec -u$UID app sh